// SPDX-License-Identifier: GPL-3.0-or-later

package es.uvigo.esei.sing.textproc.step.corenlpknowledgebasepopulation.xml.definition;

import javax.xml.bind.annotation.XmlRootElement;

import edu.stanford.nlp.pipeline.TokensRegexNERAnnotator;
import es.uvigo.esei.sing.textproc.step.xml.definition.AbstractProcessingStepParameter;

/**
 * Parameter for specifying the path a file that will be read by
 * {@link TokensRegexNERAnnotator}.
 * <p>
 * This file specifies additional NER rules
 * that will be used for matching named entities. It can be generated by the
 * CoreNLP entity extraction processing step bundled with the TextProc
 * distribution.
 * </p>
 *
 * @author Alejandro González García
 */
@XmlRootElement(name = "nerMappingsFile")
public final class NERMappingsFileProcessingStepParameter extends AbstractProcessingStepParameter {}
